// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaOG5dSu_4Y95y3YWi8cBS3fjM926kUs',
    appId: '1:1837139291:web:a2f6d90e5e0bad9763c67e',
    messagingSenderId: '1837139291',
    projectId: 'code-flow-app-e41e3',
    authDomain: 'code-flow-app-e41e3.firebaseapp.com',
    storageBucket: 'code-flow-app-e41e3.firebasestorage.app',
    measurementId: 'G-QLTNSTKM4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gNQlOWMwu2lcgfYepF1ElKBS8gdFa8s',
    appId: '1:1837139291:android:c07fd4b9099b046163c67e',
    messagingSenderId: '1837139291',
    projectId: 'code-flow-app-e41e3',
    storageBucket: 'code-flow-app-e41e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikRGdcEMYRpwrHWYyY_m29-nae7WTGRA',
    appId: '1:1837139291:ios:b8bf272ed1b4210a63c67e',
    messagingSenderId: '1837139291',
    projectId: 'code-flow-app-e41e3',
    storageBucket: 'code-flow-app-e41e3.firebasestorage.app',
    iosBundleId: 'com.example.circuitFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikRGdcEMYRpwrHWYyY_m29-nae7WTGRA',
    appId: '1:1837139291:ios:b8bf272ed1b4210a63c67e',
    messagingSenderId: '1837139291',
    projectId: 'code-flow-app-e41e3',
    storageBucket: 'code-flow-app-e41e3.firebasestorage.app',
    iosBundleId: 'com.example.circuitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBaOG5dSu_4Y95y3YWi8cBS3fjM926kUs',
    appId: '1:1837139291:web:db226d3e1ca8261363c67e',
    messagingSenderId: '1837139291',
    projectId: 'code-flow-app-e41e3',
    authDomain: 'code-flow-app-e41e3.firebaseapp.com',
    storageBucket: 'code-flow-app-e41e3.firebasestorage.app',
    measurementId: 'G-C8JDQ51D67',
  );
}
